version: "3"

services:
  web:
      container_name: searchproductsback
      restart: always
      build: .
      ports:
          - "4050:4050"
      volumes:
          - .:/usr/src/app
      #external_links:
         # - mongodb-local:mongodb-local
      #networks:
       #   - bridge
#networks:
#    bridge: